name: Build and Deploy simplejavaweb to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: target/ROOT.war

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Azure WebApp Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: terraform-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: target/ROOT.war

